-- Database Schema
-- 1. Cleanup
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE salary_details';
    EXECUTE IMMEDIATE 'DROP TABLE employees';
    EXECUTE IMMEDIATE 'DROP TABLE departments';
    EXECUTE IMMEDIATE 'DROP TABLE salary_audit';
    EXECUTE IMMEDIATE 'DROP SEQUENCE emp_seq';
    EXECUTE IMMEDIATE 'DROP SEQUENCE sal_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 2. Sequences
CREATE SEQUENCE emp_seq START WITH 101 INCREMENT BY 1;
CREATE SEQUENCE sal_seq START WITH 5001 INCREMENT BY 1;

-- 3. Tables
CREATE TABLE departments (
    dept_id NUMBER PRIMARY KEY,
    dept_name VARCHAR2(50) NOT NULL
);

CREATE TABLE employees (
    emp_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    dept_id NUMBER REFERENCES departments(dept_id),
    basic_salary NUMBER(10, 2),
    join_date DATE DEFAULT SYSDATE
);

CREATE TABLE salary_details (
    pay_id NUMBER PRIMARY KEY,
    emp_id NUMBER REFERENCES employees(emp_id),
    pay_month VARCHAR2(20), -- e.g., 'DEC-2025'
    basic NUMBER(10, 2),
    hra NUMBER(10, 2),
    bonus NUMBER(10, 2),
    tax NUMBER(10, 2),
    net_salary NUMBER(10, 2),
    processed_date DATE DEFAULT SYSDATE,
    -- Constraint to prevent paying same employee twice in same month
    CONSTRAINT unique_monthly_pay UNIQUE (emp_id, pay_month)
);

-- Audit table for the Trigger
CREATE TABLE salary_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id NUMBER,
    old_salary NUMBER,
    new_salary NUMBER,
    change_date DATE,
    changed_by VARCHAR2(50)
);

--Triggers
CREATE OR REPLACE TRIGGER trg_audit_salary
AFTER UPDATE OF basic_salary ON employees
FOR EACH ROW
BEGIN
    IF :OLD.basic_salary != :NEW.basic_salary THEN
        INSERT INTO salary_audit (emp_id, old_salary, new_salary, change_date, changed_by)
        VALUES (:OLD.emp_id, :OLD.basic_salary, :NEW.basic_salary, SYSDATE, USER);
    END IF;
END;
/

--PLSQL Package
CREATE OR REPLACE PACKAGE payroll_pkg AS
    -- Configuration constants (hardcoded for simplicity)
    c_hra_percent CONSTANT NUMBER := 0.20; -- 20% of Basic
    c_bonus_amt   CONSTANT NUMBER := 1000; -- Flat bonus
    
    -- Custom Exceptions
    e_invalid_month EXCEPTION;

    -- Functions
    FUNCTION calculate_tax(p_annual_income NUMBER) RETURN NUMBER;
    
    -- Procedures
    PROCEDURE add_employee(p_fname VARCHAR2, p_lname VARCHAR2, p_dept_id NUMBER, p_basic NUMBER);
    PROCEDURE generate_payroll(p_month VARCHAR2);
    PROCEDURE dept_wise_report;
END payroll_pkg;
/
--Package Body
CREATE OR REPLACE PACKAGE BODY payroll_pkg AS

    -- 1. Private Function: Calculate Tax
    -- Rules: 0% if < 60k, 10% if > 60k
    FUNCTION calculate_tax(p_annual_income NUMBER) RETURN NUMBER IS
        v_tax NUMBER := 0;
    BEGIN
        IF p_annual_income > 600000 THEN -- > 600k/year
            v_tax := (p_annual_income - 600000) * 0.10;
        END IF;
        
        -- Return monthly tax portion
        RETURN ROUND(v_tax / 12, 2);
    END;

    -- 2. Add Employee Helper
    PROCEDURE add_employee(p_fname VARCHAR2, p_lname VARCHAR2, p_dept_id NUMBER, p_basic NUMBER) IS
    BEGIN
        INSERT INTO employees (emp_id, first_name, last_name, dept_id, basic_salary)
        VALUES (emp_seq.NEXTVAL, p_fname, p_lname, p_dept_id, p_basic);
    END;

    -- 3. Generate Payroll for a specific month
    PROCEDURE generate_payroll(p_month VARCHAR2) IS
        v_hra NUMBER;
        v_tax NUMBER;
        v_net NUMBER;
        v_annual_est NUMBER;
    BEGIN
        -- Loop through all employees
        FOR r_emp IN (SELECT * FROM employees) LOOP
            
            -- Logic Calculations
            v_hra := r_emp.basic_salary * c_hra_percent;
            v_annual_est := (r_emp.basic_salary + v_hra + c_bonus_amt) * 12;
            v_tax := calculate_tax(v_annual_est);
            v_net := (r_emp.basic_salary + v_hra + c_bonus_amt) - v_tax;
            
            BEGIN
                INSERT INTO salary_details (
                    pay_id, emp_id, pay_month, basic, hra, bonus, tax, net_salary
                ) VALUES (
                    sal_seq.NEXTVAL, r_emp.emp_id, p_month, 
                    r_emp.basic_salary, v_hra, c_bonus_amt, v_tax, v_net
                );
            EXCEPTION
                WHEN DUP_VAL_ON_INDEX THEN
                    DBMS_OUTPUT.PUT_LINE('Skipping: Payroll already processed for Emp ID ' || r_emp.emp_id);
            END;
        END LOOP;
        
        DBMS_OUTPUT.PUT_LINE('Payroll generation complete for ' || p_month);
    END;

    -- 4. Department-wise Report (Using Explicit Cursor)
    PROCEDURE dept_wise_report IS
        CURSOR c_dept_summary IS
            SELECT d.dept_name, COUNT(e.emp_id) as emp_count, SUM(e.basic_salary) as total_basic
            FROM departments d
            JOIN employees e ON d.dept_id = e.dept_id
            GROUP BY d.dept_name;
            
        r_summary c_dept_summary%ROWTYPE;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('--- DEPARTMENT SALARY SUMMARY ---');
        OPEN c_dept_summary;
        LOOP
            FETCH c_dept_summary INTO r_summary;
            EXIT WHEN c_dept_summary%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE('Dept: ' || RPAD(r_summary.dept_name, 10) || 
                                 ' | Staff: ' || r_summary.emp_count || 
                                 ' | Total Basic: $' || r_summary.total_basic);
        END LOOP;
        CLOSE c_dept_summary;
    END;

END payroll_pkg;
/

--Setup + Testing
SET SERVEROUTPUT ON;

-- 1. Setup Reference Data
INSERT INTO departments VALUES (1, 'IT');
INSERT INTO departments VALUES (2, 'HR');
INSERT INTO departments VALUES (3, 'Sales');

BEGIN
    -- 2. Add Employees
    payroll_pkg.add_employee('Alice', 'Smith', 1, 50000); -- IT
    payroll_pkg.add_employee('Bob', 'Jones', 1, 60000);   -- IT
    payroll_pkg.add_employee('Charlie', 'Brown', 2, 45000); -- HR
    
    COMMIT; -- Save employees
    
    -- 3. Run Payroll for December
    payroll_pkg.generate_payroll('DEC-2025');
    
    -- 4. Generate Reports
    payroll_pkg.dept_wise_report;
    
    -- 5. Test Audit Trigger (Update ram's Salary)
    UPDATE employees SET basic_salary = 65000 WHERE first_name = 'Ram';
    COMMIT;
END;
/

-- Verify Audit Log
SELECT * FROM salary_audit;

-- Verify Payslips
SELECT * FROM salary_details;
